"""roadmap and teams

Revision ID: b53caf4aefee
Revises: 680cb45c71a0
Create Date: 2025-12-01 21:46:45.432863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b53caf4aefee'
down_revision = '680cb45c71a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roadmap_phases',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_week', sa.Integer(), nullable=True),
    sa.Column('end_week', sa.Integer(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('roadmap_phases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_roadmap_phases_organization_id'), ['organization_id'], unique=False)

    op.create_table('teams',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('member_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teams_organization_id'), ['organization_id'], unique=False)

    op.create_table('roadmap_milestones',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=True),
    sa.Column('phase_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('week', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['phase_id'], ['roadmap_phases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('roadmap_milestones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_roadmap_milestones_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_roadmap_milestones_phase_id'), ['phase_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roadmap_milestones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roadmap_milestones_phase_id'))
        batch_op.drop_index(batch_op.f('ix_roadmap_milestones_organization_id'))

    op.drop_table('roadmap_milestones')
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teams_organization_id'))

    op.drop_table('teams')
    with op.batch_alter_table('roadmap_phases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roadmap_phases_organization_id'))

    op.drop_table('roadmap_phases')
    # ### end Alembic commands ###
